namespace Tbl;

table DungeonRotationReward {
  no: int32;
  dungeon_no: int32;
  difficulty: int32;
  clear_reward_no_1: int32;
  clear_reward_amount_1: int32;
  clear_reward_no_2: int32;
  clear_reward_amount_2: int32;
  clear_reward_no_3: int32;
  clear_reward_amount_3: int32;
  clear_reward_no_4: int32;
  clear_reward_amount_4: int32;
  clear_reward_no_5: int32;
  clear_reward_amount_5: int32;
  clear_reward_no_6: int32;
  clear_reward_amount_6: int32;
  clear_reward_no_7: int32;
  clear_reward_amount_7: int32;
  clear_reward_no_8: int32;
  clear_reward_amount_8: int32;
  clear_reward_no_9: int32;
  clear_reward_amount_9: int32;
  clear_reward_no_10: int32;
  clear_reward_amount_10: int32;
}

table DungeonRotationRewardTable {
  json: [DungeonRotationReward];
}

root_type DungeonRotationRewardTable;
