namespace Tbl;

table EventChallengeStageSetting {
  no: int32;
  event_group: int32;
  event_number: int32;
  event_stage_phase: int32;
  event_phase_sno: int32;
  stage_name_sno: int32;
  level_limit: int32;
  hero_no_1: int32;
  hero_grade_1: int32;
  level_1: int32;
  hero_no_2: int32;
  hero_grade_2: int32;
  level_2: int32;
  hero_no_3: int32;
  hero_grade_3: int32;
  level_3: int32;
  hero_no_4: int32;
  hero_grade_4: int32;
  level_4: int32;
  hero_no_5: int32;
  hero_grade_5: int32;
  level_5: int32;
  map: string;
  formation_type: int32;
  global_volume: int32;
  battle_time: int32;
  only_rental: int32;
  open_date: string;
}

table EventChallengeStageSettingTable {
  json: [EventChallengeStageSetting];
}

root_type EventChallengeStageSettingTable;
