namespace Tbl;

table SingleRaidRankReward {
  no: int32;
  level_group: int32;
  rank_from: int32;
  rank_to: int32;
  reward_item1_no: int32;
  reward_item1_amount: int32;
  reward_item2_no: int32;
  reward_item2_amount: int32;
  reward_item3_no: int32;
  reward_item3_amount: int32;
  reward_item4_no: int32;
  reward_item4_amount: int32;
  reward_item5_no: int32;
  reward_item5_amount: int32;
}

table SingleRaidRankRewardTable {
  json: [SingleRaidRankReward];
}

root_type SingleRaidRankRewardTable;
