namespace Tbl;

table SingleRaidBossGroggyTrigger {
  single_raid_boss_no: int32;
  groggy_skill_code_1: int32;
  groggy_skill_code_2: int32;
  groggy_skill_code_3: int32;
  groggy_skill_code_4: int32;
  groggy_skill_code_5: int32;
  groggy_skill_code_6: int32;
  groggy_skill_code_7: int32;
  groggy_skill_code_8: int32;
  groggy_skill_code_9: int32;
  groggy_skill_code_10: int32;
  condition_group: int32;
  recovery_duration: int32;
  sound_path: string;
}

table SingleRaidBossGroggyTriggerTable {
  json: [SingleRaidBossGroggyTrigger];
}

root_type SingleRaidBossGroggyTriggerTable;
