namespace Tbl;

table Dungeon {
  no: int32;
  name_sno: int32;
  desc_sno: int32;
  list_sno: int32;
  dungeon_type: int32;
  rotation_priority: int32;
  hero_count_max: int32;
  hero_level_min: int32;
  hero_grade_min: int32;
  race_buff_no: string;
  dungeon_buff_no: string;
  monster_tribe: int32;
  advantage_tribe: int32;
  disadvantage_tribe: int32;
  dungeon_list_image: string;
  dungeon_info_image: string;
  dungeon_map: string;
  dungeon_leveldesign: string;
  mission_group_no: int32;
  minimap_title_sno: int32;
  hide_ui: string;
  is_usable: int32;
  sound_bgm: string;
  sound_ambience: string;
}

table DungeonTable {
  json: [Dungeon];
}

root_type DungeonTable;
