namespace Tbl;

table EventRankRaid {
  no: int32;
  event_group: int32;
  event_number: int32;
  stage_no: int32;
  battle_view_type: int32;
  help_desc_sno: int32;
  challenge_no_1: int32;
  challenge_bonus_1: float;
  challenge_no_2: int32;
  challenge_bonus_2: float;
  challenge_no_3: int32;
  challenge_bonus_3: float;
  bg_path: string;
  bg_position: string;
  event_bg_path: string;
  sound_path: string;
  open_date: string;
}

table EventRankRaidTable {
  json: [EventRankRaid];
}

root_type EventRankRaidTable;
