namespace Tbl;

table EventSelectStageReward {
  no: int32;
  first_clear_reward_no: int32;
  first_clear_reward_amount: int32;
  reward_item_no_1: int32;
  reward_item_amount_1: int32;
  reward_item_no_2: int32;
  reward_item_amount_2: int32;
  reward_item_no_3: int32;
  reward_item_amount_3: int32;
  reward_item_no_4: int32;
  reward_item_amount_4: int32;
  reward_item_no_5: int32;
  reward_item_amount_5: int32;
}

table EventSelectStageRewardTable {
  json: [EventSelectStageReward];
}

root_type EventSelectStageRewardTable;
